config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  resources :users do
    resources :cocktails
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :ingredients, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cocktails, dependent: :destroy
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: %i[ show edit update destroy ]

  # GET /cocktails or /cocktails.json
  def index
    @cocktails = Cocktail.all
  end

  # GET /cocktails/1 or /cocktails/1.json
  def show
    @user = User.find(params[:user_id])
    @cocktail = Cocktail.find(params[:id])
    render :show
  end

  # GET /cocktails/new
  def new
    @user = User.find(params[:user_id])
    @cocktail = @user.cocktails.new
    render :new
  end

  # GET /cocktails/1/edit
  def edit
    @user = User.find(params[:user_id])
    @cocktail = Cocktail.find(params[:id])
    render :edit
  end

  # POST /cocktails or /cocktails.json
  def create
    @user = User.find(params[:user_id])
    @cocktail = @user.cocktails.new(cocktail_params)
    if @cocktail.save
      redirect_to user_path(@user)
    else
      render :new
    end
  
  end

  # PATCH/PUT /cocktails/1 or /cocktails/1.json
  def update
    @cocktail = Cocktail.find(params[:id])
    if @cocktail.update(cocktail_params)
      redirect_to user_path(@cocktail.user)
    else
      @user = User.find(params[:user_id])
      render :edit
    end

  end

  # DELETE /cocktails/1 or /cocktails/1.json
  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to user_path(@cocktail.user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cocktail_params
      params.require(:cocktail).permit(:name, :ingredients)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
    render :index
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
    render :show
  end

  # GET /users/new
  def new
    @user = User.new
    render :new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    render :edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end

  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cocktails/_form.html.erb
<%= render 'layouts/errors', :object => @cocktail %>

<%= form_for [@user, @cocktail] do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :ingredients %>
    <%= f.text_area :ingredients %>

    <p><%= f.submit %></p>

<% end %>

app/views/cocktails/edit.html.erb
<h1>Editing Cocktail</h1>

<%= render 'form', locals: { user: @user, cocktail: @cocktail } %>

<%= link_to 'Show', [@user, @cocktail] %> |
<%= link_to 'Back', user_path(@user) %>

app/views/cocktails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cocktails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ingredients</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cocktails.each do |cocktail| %>
      <tr>
        <td><%= cocktail.name %></td>
        <td><%= cocktail.ingredients %></td>
        <td><%= link_to 'Show', cocktail %></td>
        <td><%= link_to 'Edit', edit_cocktail_path(cocktail) %></td>
        <td><%= link_to 'Destroy', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cocktail', new_cocktail_path %>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>
<%= render 'layouts/errors', :object => @user %>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', user_path(@user) %>

app/views/cocktails/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @cocktail.name %>
</h2>

<p>
  <strong>Ingredients:</strong>
  <%= @cocktail.ingredients %>
</p>

<%= link_to 'Edit', edit_user_cocktail_path(@user, @cocktail) %> |
<%= link_to 'Delete', user_cocktail_path(@user, @cocktail),
            :data => {:confirm => "Are You Sure?",
            :method => "delete"} %> |
<%= link_to 'Back', user_path(@user) %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please Fix These Errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocktails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @user.username %>
</h2>

<h3>Favorite Cocktails</h3>

<% if @user.cocktails.any? %>


  <% @user.cocktails.each do |cocktail| %>

    <ul>
      <li>
        <%= link_to cocktail.name, user_cocktail_path(@user, cocktail) %>
      </li>
    </ul>

  <% end %>
<% else %>
  <p>No favorites (yet)</p>
<% end %>

<%= link_to "Add a favorite", new_user_cocktail_path(@user) %> |
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Delete user', user_path(@user),
          :data => {:confirm => "Are you sure?",
                    :method => "delete"} %> |
<%= link_to 'Back', users_path %>